# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08d9bc1b3a8fc9e4287e8c37f44c6a1e50a95a03adffc19ac26e36fb18ef4c282ea8ac354af4a00818cbff339ada1b03659199de63924311b206a5bbfb34fef1

test:
  secret_key_base: 6a70a50867937f43b87bcc4bfd5f82ab232245f5b30c3b4092f90d934d0e7c437f323391dc13b7fae94bb94acbdbf1ffcd8a75a7118b7b59ce1d8762ad5892b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
